---
# tasks file for db

- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Import mongo installation tasks
  import_tasks: install_mongo.yml
  become: yes

- name: Import mongo configuration tasks
  import_tasks: config_mongo.yml
